### PR TITLE
Cancel async tasks correctly

### PR DESCRIPTION
**Pull request by jiri-one**
Only on test is broken: FAILED tests/test_remove_output_dir.py::test_do_not_overwrite_existing_dir - RuntimeError: dictionary changed size during iteration

### CODE REVIEW

**Comment by jiri-one** [comment]
If I understood correctly, the problem was that the task that processed the 'smile.png' file was done faster than freezeyt could get to it to cancel it. That's why I made a copy of the inprogress_tasks dictionary's keys, and if I didn't find a key in inprogress_tasks, I didn't try to cancel it. I guess I could also do a verification there that the task is already in done_tasks. The tests are already passing, not passing Python 3.6 due to the fact that I'm using asyncio.get_running_loop , this can be solved, but I prefer to do it after checking :).

**Comment by encukou** [comment]
Can you use [dict.popitem](https://docs.python.org/3/library/stdtypes.html#dict.popitem)?

First `cancel()` all tasks (that is, *schedule* cancellation), and only after that, `await` them all. That way all the tasks will be cleaning up, rather than continuing regular work, while you wait.

`run_coroutine_threadsafe` schedules a task, but doesn't wait for it to be finished. So we won't get any exceptions, and the task might even end up unfinished when freezeyt exits.

**Comment by jiri-one** [comment]
I've tried to incorporate all your notes @encukou

**Comment by jiri-one** [comment]
I have thought that my test test_cancellederror_was_raised should work, but it doesn't ...

**Review by encukou — APPROVED** [review]

**Pull request merged**
