### PR TITLE
Fix redirect to same static file `/` -> `/index.html`

### LINKED ISSUE #363: Handle redirects from .../index.html to .../
Also, if `/some/url` redirects to `/some/url/` (with a trailing slash), freezeyt should follow the redirect automatically, bypassing `status_handlers`.

### PR DESCRIPTION
**Pull request by nappex**
fix #363 

Web application (e.g. `flask`) can define two different URLs with different page content and those URLs would be saved by `Freezeyt` to same file path. The most common case would be with URLs `/` and `/index.html`, both will be saved to file path `/index.html`.  `Freezeyt` freeze the content of the first occurred URL, the rest URLs invokes a warning message about requesting one file path from more URLs, because of async approach the order of URLs is not same every time. So sometimes is saved content of `/` other time `/index.html`.

When web application can can define two different URLs, which share a same output static file, redirecting between those URLs are not recognized by web app as one file in output by freezing. So `Freezeyt` has to solve it on its own.

### CODE REVIEW

**Comment by nappex** [comment]
Currently we've got an error `InfiniteRedirection`

**Comment by nappex** [comment]
`flask.redirect` raises different errors than `flask.Response`. The [commit](https://github.com/encukou/freezeyt/pull/374/commits/cd4d203c4dfd31ace0e2a57015e0088ebfa68bc6) which has changed `Response` to `redirect`.

**Comment by nappex** [comment]
What I need to understand:
1. how are redirects handled, how we create a `new task` from redirect_to url and saving the new `content`, I do not see the asking application for it.
2. how it works the await for `task.asyncio_task`

**Comment by encukou** [comment]
No. *Creating* a task `asyncio.create_task` will start it.
`await` waits until the task done and gives you the result. If the task was already done, it only gives you the result.

**Comment by nappex** [comment]
PR should be done now, maybe improve tests parametrize should be done yet.

**Review by encukou — APPROVED** [review]

**Pull request merged**
