### PR TITLE
Manage pages to freeze as Task objects

### PR DESCRIPTION
**Pull request by encukou**
In preparation for handling redirects, this makes freezeyt manage pages to freeze (and pages it already froze) as Task objects.

### CODE REVIEW

**Comment by nappex** [comment]
Have you pushed last commits ?

**Comment by encukou** [comment]
No. As you can see, this fails on older versions of Python – I haven't checked those before pushing. (And it needs a rebase, the `cli.py` change isn't needed now.)

I think fixing this might be a nice topic for Tuesday. But in short:
- [dataclasses](https://docs.python.org/3/library/dataclasses.html) is new in Python 3.7, but has a [backport package](https://pypi.org/project/dataclasses/) for 3.6. For putting version-specific dependencies in `requirements.txt`, there are [environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers).
- `set[URL]` was [added in 3.9](https://www.python.org/dev/peps/pep-0585/), but a string – `"set[URL]"` – should work well.

**Comment by nappex** [comment]
I understand. I wanted make a note to one line of code from stream.

'assert ".." in path.parts'

if it is not better to handle this situation

**Comment by encukou** [comment]
> 'assert ".." in path.parts'

That's not in this PR yet.

**Review by nappex — APPROVED** [review]

**Pull request merged**
