### PR TITLE
Add option to pass configuration in a variable

### PR DESCRIPTION
**Pull request by adelpopelkova**
Fixes https://github.com/encukou/freezeyt/issues/133

At the moment it doesn't really work.

### CODE REVIEW

**Comment by adelpopelkova** [comment]
At the moment there is only one test added. (Should I add more?) While I was adding this feature, I tested the changes using the blog app, where I changed the configuration. In the terminal I used:
```
python -m freezeyt freezeyt_blog.app freezeyt_blog/build -C freezeyt_blog.app:config
```
The problem with this is, that I wasn't able to make it work on Windows. (On Linux it works.)

**Comment by encukou** [comment]
Thanks for fixing the Windows build!
I think one test is fine.

There's one more thing to think about: what happens if the user passes both the `-c` and `-C` options?

**Comment by adelpopelkova** [comment]
> The problem with this is, that I wasn't able to make it work on Windows. (On Linux it works.)

Tried it today and it works also on Windows. (I have no idea where the problem was.) 🎉

**Comment by encukou** [comment]
If the user passes both the `-c` and `-C` options, one of them is ignored. It would be better to raise an error in this case.
([click.UsageError](https://click.palletsprojects.com/en/8.0.x/api/?highlight=error#click.UsageError) might be useful.)

**Review by encukou — APPROVED** [review]

**Comment by encukou** [comment]
Looks good!
Here's a detail that might be interesting to explore: there are now several ways of checking the arguments:
* `if config_file` ( and config_var)
* `elif config_file != None:`
* `elif config_var is not None:`

How are they different?

**Comment by adelpopelkova** [comment]
> Here's a detail that might be interesting to explore: there are now several ways of checking the arguments:
> 
>     * `if config_file` ( and config_var)
> 
>     * `elif config_file != None:`
> 
>     * `elif config_var is not None:`
> 
> 
> How are they different?

From what I have found:
The first one (`if config_file`) - `if` automatically calls `bool` so this is basically `if bool(config_file)`. The output of `bool` is `Flase` when given an empty string, dictionary, None etc. The variable `config_file` is an open file (`<class '_io.TextIOWrapper'>`). `config_var` is a string.

The second one (`elif config_file != None:`) - `==` calls the `__eq__` method (of the object on the left) and this checks if the value of the object is the same (however, this one can be modified) and since `None` is a singleton and is only once in the memory, the third way of checking the arguments (`elif config_var is not None:`) should be preferred, because `is` only checks if the objects' IDs are the same. (And since it doesn't have to look up any methods it should be faster and also safer since it can't be modified. One of the articles said that `is` is implemented in C, but I wasn't able to find it in the source code. 😄)

Flake8 has an Error _E711 - comparison to None should be 'if condition is not None:'_, PEP8 doesn't mention it. Somewhere I also read that using `is not None` instead of `!= None` is a "best practice".

(Most of it was taken from these articles [from Real Python](https://realpython.com/python-is-identity-vs-equality/) (I found this one the most useful), a [question](https://stackoverflow.com/questions/2209755/python-operation-vs-is-not)  from Stackoverflow and this [blog post](https://lerner.co.il/2015/06/16/why-you-should-almost-never-use-is-in-python/).)

Regarding our code, I am not really sure, how someone could break the comparison in this use case (`elif config_file != None:`), but if we want to make it "unbreakable", than probably `is not None` is a better option. (And the code is now a bit inconsistent, but that is a minor reason.) With the first one (`if config_file and config_var`), I would say that this is fine, because sooner or later the code will end up with an error. Of course if there are reasons that I am not aware of, why some other comparison option would be preferred than it probably is worth changing it.

> Here's a detail that might be interesting to explore

It was very interesting to explore, thanks for the suggestion. By the way, feel free to correct anything that isn't correct. 😄

**Comment by adelpopelkova** [comment]
And a few questions about the commits - should I make it three (1. Fixing the blog build, 2. Adding the config and 3. Raising an error) or two commits (1. Fixing the blog build and 2. Adding the config and raising an error).

And should there also be a test for the error when both config options are passed or not?

**Comment by encukou** [comment]
> One of the articles said that is is implemented in C, but I wasn't able to find it in the source code.

There's a `Py_Is` [function](https://github.com/python/cpython/blob/f92b9133ef67e77605cbd315b6b6c81036ce110e/Objects/object.c#L2280-L2283) and [a macro](https://github.com/python/cpython/blob/f92b9133ef67e77605cbd315b6b6c81036ce110e/Include/object.h#L127) with the same effect. Both are very simple.
The `is`/`is not` operator calls that and has some more complications like converting the result to `True`/`False`: https://github.com/python/cpython/blob/f92b9133ef67e77605cbd315b6b6c81036ce110e/Python/ceval.c#L3504-L3516

---

Our code could be “broken” by passing an empty string to `-c` or `-C`. That's not much breakage; the effect would be about the same as any other invalid path or variable name. The user just gets a slightly worse error message.
The *inconsistency* tends to be a bit worse problem in general (rather than in this specific case), because the program can get into code paths the programmer didn't anticipate.
So, it's best to choose one and stick to it :)

Generally, `is None` is a bit faster, but I often use `== None` because it's more approachable.  I don't teach `is` (and all these nuances) in the beginner course. When you're so deep into optimization that `==` is not fast enough, there are better optimization techniques to use.
On the other hand, tools like `mypy` find stronger guarantees in code that uses `is` rather than `==`, so that might be a reason to use that.
The functional difference between `is None` and `== None` is only seen with custom classes that define `__eq__` weirdly; if someone is using a class like that, they probably have a reason for weird behavior. In practice, they're equivalent.

---

As for organizing the commits, I'd go for only two commits: I see adding the error as a fixing an issue in the first commit. But three commits is perfectly fine.

**Comment by adelpopelkova** [comment]
The changes are rebased. I accidentally clicked the re-request review button, there aren't any new code changes. 🙃

**Comment by encukou** [comment]
Great, thank you!

**Pull request merged**
