### PR TITLE
Test Django Framework

### PR DESCRIPTION
**Pull request by nappex**
Add django project with two apps 

- demo_app
- demo_app_2pages

Django Project with apps was created by tutorial  found in [official docs](https://docs.djangoproject.com/en/3.1/intro/tutorial01/)

### CODE REVIEW

**Comment by nappex** [comment]
*Note: How to ignore pyflakes error `imported but unused`:*

**Not working** solutions are:

between code and `#` was two or one space
 ```python
from django.db import models  # silence pyflakes
```
 ```python
from django.db import models  # NOQA
```
 ```python
from django.db import models  # flake8: noqa
```
 ```python
from django.db import models  # noqa
```
 ```python
from django.db import models  # noqa: F841
```

All tries mentioned above could be used only with flake8 in my opinion

**Working** solution is:
 ```python
from django.db import models

__all__ = ['models']
```

**Comment by nappex** [comment]
Remove hardcoded links with templates system is there [removing hardcoded urls](https://docs.djangoproject.com/en/3.1/intro/tutorial03/#removing-hardcoded-urls-in-templates)

**Comment by nappex** [comment]
Problem with freeze django project to find module with app:
```python
python -m freezeyt tests.fixtures.demo_project_django.demo_project.app build_django
```
Error occures:
```python
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'demo_project'
```

**Comment by encukou** [comment]
Did you set `PYTHONPATH` to the directory with `demo_project_django`?
This isn't necessary for other test apps, since they don't import anything, but for a multi-file app it will be necessary.

**Comment by nappex** [comment]
No, I don't 🙂

**Comment by nappex** [comment]
PYTHONPATH helped, but there is occurs another problem
My steps were:
```shell
$ export PYTHONPATH=freezeyt/tests/fixtures/demo_project_django/

$ python -m freezeyt tests.fixtures.demo_project_django.demo_project.app build_django

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/stroch/Documents/Python/develop/freezeyt/freezeyt/__main__.py", line 3, in <module>
    main()
  File "/Users/stroch/.virtualenvs/freezeyt/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/stroch/.virtualenvs/freezeyt/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/stroch/.virtualenvs/freezeyt/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/stroch/.virtualenvs/freezeyt/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/stroch/Documents/Python/develop/freezeyt/freezeyt/cli.py", line 65, in main
    freeze(app, dest_path, cli_params)
  File "/Users/stroch/Documents/Python/develop/freezeyt/freezeyt/freezing.py", line 177, in freeze
    result = app(environ, start_response)
  File "/Users/stroch/.virtualenvs/freezeyt/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 132, in __call__
    request = self.request_class(environ)
  File "/Users/stroch/.virtualenvs/freezeyt/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 87, in __init__
    self._stream = LimitedStream(self.environ['wsgi.input'], content_length)
KeyError: 'wsgi.input'
```

**Comment by nappex** [comment]
3. **Problem to find path to app static folder**

Unfortunately, image with static folder wasn't created so another error occured:

```shell
  File "/Users/stroch/Documents/Python/develop/freezeyt/freezeyt/freezing.py", line 113, in start_response
    raise ValueError("Found broken link.")
ValueError: Found broken link.
```
for link:
```shell
Saving to build_django/image_page.html
link: http://localhost:8000/static/smile.png
path_info: /static/smile.png
b'/static/smile.png'
b'/'
Not Found: /static/smile.png
```
That's really strange when I startup my web app by `python manage.py runserver` then link -> `http://localhost:8000/static/smile.png` is OK in web browser - I see the image

I supposed that problem will be in path_info, because we need `demo_app/static/smile.png`, but we got `/static/smile.png`

**Comment by encukou** [comment]
Code [304 Not Modified](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304) means the server is saying that the file wasn't changed; the browser should use a copy it already has downloaded. (For this to work, the request needs to indicate which copy the browser has available, using headers like [`If-Modified-Since`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since) or [`If-None-Match`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match).)

Read https://docs.djangoproject.com/en/3.1/howto/static-files/#serving-static-files-in-development instead of the docs for production. Freezeyt should be used with development servers, not production ones. (Remind me to explain more on the stream.)

**Comment by nappex** [comment]
I've set up static file exactly as described in https://docs.djangoproject.com/en/3.1/howto/static-files/#serving-static-files-in-development

Django application works...
```$ python manage.py collectstatic``` works 

But freezeyt can not still found static files:
```shell
link: http://localhost:8000/demo_app/static/demo_app/smile.png
path_info: /demo_app/static/demo_app/smile.png
b'/demo_app/static/demo_app/smile.png'
b'/'
Not Found: /demo_app/static/demo_app/smile.png
```

**Comment by nappex** [comment]
I don't know which other tests should be beneficial.... Could you give some other idea about other beneficial tests

I supposed that these test could be fine to add:

- css as static file

**Comment by encukou** [comment]
It should be enough to test CSS files with Flask. It's not that different from images, and the Django admin already includes CSS.

**Review by encukou — APPROVED** [review]

**Pull request merged**
